baseURL = "https://adrianperez.me/"
languageCode = "en-us"
title = "Adrian Perez Rodriguez"
theme = "resume"

[params]
    firstName = "Adrian"
    lastName = "Perez"
    address = "Meggen, Switzerland"
    contactNote = "Digital Native and Webenthusiast"
    profileImage = "img/me.jpg"
    email = "me@adrianperez.me"
    description = "I am a CRM developer in the Web Development Services department at AMAG Corporate Services AG, currently live in Meggen, Switzerland. My interests range from programming to travel. I am also interested in DIY, sports, and technology."
    favicon = "favicon.ico"
    showQr = false
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = false
    showExperience = true
    showEducation = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/adpe"
    icon = "linkedin"

[[params.handles]]
    name = "Xing"
    link = "https://www.xing.com/profile/Adrian_Perez24/cv"
    icon = "xing"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/adpe/"
    icon = "github"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/story/adpe"
    icon = "stack-overflow"

[[params.handles]]
    name = "Telegram"
    link = "https://t.me/adpe90"
    icon = "telegram"

[[params.handles]]
	name = "Signal"
	link = "https://signal.group/#CjQKIPTT3JKSxGiXBnhneQDkZl1AWSLtKZrtKeRPol2UnNZyEhA2zEqeG3rdV8iaLwtKkr4U"
	icon = "signalapp"
	
[[params.handles]]
	name = "Polarsteps"
	link = "https://www.polarsteps.com/AdrianPerez"
	icon = "icomoon-polarsteps"

[params.google.analytics]
    trackerID = "UA-129035485-1"

[params.google.tagmanager]
    trackerID = "GTM-TRSMZDH"

[outputs] #only required for search
    home = ["HTML", "JSON"]
