baseURL = "https://adrianperez.me/"
languageCode = "en-us"
title = "Adrian Perez Rodriguez"
theme = "resume"

[params]
    firstName = "Adrian"
    lastName = "Perez"
    address = "Brig, Switzerland"
    contactNote = "Digital Native and Webenthusiast"
    profileImage = "img/me.jpg"
    email = "p.adrian@gmx.ch"
    description = "I am a web developer at Fernfachhochschule Schweiz currently living in Brig, Switzerland. My interests range from programming to travel. I am also interested in DIY, sports, and technology."
    favicon = "favicon.ico"
    showQr = false
    showSkills = true
    showProjects = false
    showOpenSource = true
    showPublications = false
    showExperience = true
    showEducation = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/perez-r-adrian/"
    icon = "linkedin"

[[params.handles]]
    name = "Xing"
    link = "https://www.xing.com/profile/Adrian_PerezRodriguez2"
    icon = "xing"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/adpe/"
    icon = "github"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/story/7262345"
    icon = "stack-overflow"

[[params.handles]]
    name = "Telegram"
    link = "https://t.me/adpe90"
    icon = "telegram"
	
[[params.handles]]
	name = "Polarsteps"
	link = "https://www.polarsteps.com/AdrianPerez"
	icon = "icomoon-polarsteps"

[params.google.analytics]
    trackerID = "UA-129035485-1"

[params.google.tagmanager]
    trackerID = "GTM-TRSMZDH"

[outputs] #only required for search
    home = ["HTML", "JSON"]
