[build.environment]
  NODE_VESION = "22.18.0"
  HUGO_VERSION = "0.148.2"
  HUGO_ENV = "production"
  TZ = "Europe/Zurich"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"