[[headers]]
  for = "/fonts/*"
  [headers.values]
    Access-Control-Allow-Origin = '''
    https://adrianperez.me,
    https://adrianperez.swiss,
    https://perez.swiss'''
    Content-Type = "font/ttf"